###############################################################################
# Created by write_sdc
###############################################################################
current_design tt_um_tqv_peripheral_harness
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_clock_uncertainty -rise_from [get_clocks {clk}] -fall_to [get_clocks {clk}]  -hold 2.5000
set_clock_uncertainty -rise_from [get_clocks {clk}] -fall_to [get_clocks {clk}]  -setup 2.5000
set_clock_uncertainty -fall_from [get_clocks {clk}] -rise_to [get_clocks {clk}]  -hold 2.0000
set_clock_uncertainty -fall_from [get_clocks {clk}] -rise_to [get_clocks {clk}]  -setup 2.0000
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ena}]
set_input_delay 1.5000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[0]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[0]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[1]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[1]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[2]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[2]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[3]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[3]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[4]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[4]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[5]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[5]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[6]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[6]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ui_in[7]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ui_in[7]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[0]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[0]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[1]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[1]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[2]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[2]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[3]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[3]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[4]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[4]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[5]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[5]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[6]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[6]}]
set_input_delay 2.4000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_in[7]}]
set_input_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_in[7]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[0]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[0]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[1]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[1]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[2]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[2]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[3]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[3]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[4]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[4]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[5]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[5]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[6]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[6]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_oe[7]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_oe[7]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[0]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[0]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[1]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[1]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[2]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[2]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[3]}]
set_output_delay 1.8000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[3]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[4]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[4]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[5]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[5]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[6]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[6]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uio_out[7]}]
set_output_delay 6.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uio_out[7]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[0]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[1]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[2]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[3]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[4]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[5]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[6]}]
set_output_delay 1.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[7]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {uio_oe[7]}]
set_load -pin_load 0.0334 [get_ports {uio_oe[6]}]
set_load -pin_load 0.0334 [get_ports {uio_oe[5]}]
set_load -pin_load 0.0334 [get_ports {uio_oe[4]}]
set_load -pin_load 0.0334 [get_ports {uio_oe[3]}]
set_load -pin_load 0.0334 [get_ports {uio_oe[2]}]
set_load -pin_load 0.0334 [get_ports {uio_oe[1]}]
set_load -pin_load 0.0334 [get_ports {uio_oe[0]}]
set_load -pin_load 0.0334 [get_ports {uio_out[7]}]
set_load -pin_load 0.0334 [get_ports {uio_out[6]}]
set_load -pin_load 0.0334 [get_ports {uio_out[5]}]
set_load -pin_load 0.0334 [get_ports {uio_out[4]}]
set_load -pin_load 0.0334 [get_ports {uio_out[3]}]
set_load -pin_load 0.0334 [get_ports {uio_out[2]}]
set_load -pin_load 0.0334 [get_ports {uio_out[1]}]
set_load -pin_load 0.0334 [get_ports {uio_out[0]}]
set_load -pin_load 0.0334 [get_ports {uo_out[7]}]
set_load -pin_load 0.0334 [get_ports {uo_out[6]}]
set_load -pin_load 0.0334 [get_ports {uo_out[5]}]
set_load -pin_load 0.0334 [get_ports {uo_out[4]}]
set_load -pin_load 0.0334 [get_ports {uo_out[3]}]
set_load -pin_load 0.0334 [get_ports {uo_out[2]}]
set_load -pin_load 0.0334 [get_ports {uo_out[1]}]
set_load -pin_load 0.0334 [get_ports {uo_out[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ena}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
