/* Generated by Yosys 0.61+21 (git sha1 967b47d98, clang++ 18.1.3 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "synchronizer" *)
(* src = "synchronizer.sv:6.1-24.10" *)
module \$paramod$1b0ac1a71bf6235a146509cbb11b370bdc3def37\synchronizer (clk, data_in, data_out);
  (* src = "synchronizer.sv:8.15-8.18" *)
  input clk;
  wire clk;
  (* src = "synchronizer.sv:9.27-9.34" *)
  input [0:0] data_in;
  wire [0:0] data_in;
  (* src = "synchronizer.sv:10.28-10.36" *)
  output [0:0] data_out;
  wire [0:0] data_out;
  (* src = "synchronizer.sv:12.21-12.30" *)
  wire [0:0] \data_sync[0] ;
  (* src = "synchronizer.sv:12.21-12.30" *)
  wire [0:0] \data_sync[1] ;
  (* src = "synchronizer.sv:12.21-12.30" *)
  wire [0:0] \data_sync[2] ;
  (* src = "synchronizer.sv:18.35-18.111" *)
  \$paramod\reclocking\WIDTH=s32'00000000000000000000000000000001  \gen_reclocking[0].reclocking_i0  (
    .clk(clk),
    .data_in(data_in),
    .data_out(\data_sync[1] )
  );
  (* src = "synchronizer.sv:18.35-18.111" *)
  \$paramod\reclocking\WIDTH=s32'00000000000000000000000000000001  \gen_reclocking[1].reclocking_i0  (
    .clk(clk),
    .data_in(\data_sync[1] ),
    .data_out(data_out)
  );
  assign \data_sync[0]  = data_in;
  assign \data_sync[2]  = data_out;
endmodule

(* dynports =  1  *)
(* hdlname = "synchronizer" *)
(* src = "synchronizer.sv:6.1-24.10" *)
module \$paramod$e209ecfe3425492cab30fe3f17f0ed06a3da57b8\synchronizer (clk, data_in, data_out);
  (* src = "synchronizer.sv:8.15-8.18" *)
  input clk;
  wire clk;
  (* src = "synchronizer.sv:9.27-9.34" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "synchronizer.sv:10.28-10.36" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "synchronizer.sv:12.21-12.30" *)
  wire [7:0] \data_sync[0] ;
  (* src = "synchronizer.sv:12.21-12.30" *)
  wire [7:0] \data_sync[1] ;
  (* src = "synchronizer.sv:12.21-12.30" *)
  wire [7:0] \data_sync[2] ;
  (* src = "synchronizer.sv:18.35-18.111" *)
  \$paramod\reclocking\WIDTH=s32'00000000000000000000000000001000  \gen_reclocking[0].reclocking_i0  (
    .clk(clk),
    .data_in(data_in),
    .data_out(\data_sync[1] )
  );
  (* src = "synchronizer.sv:18.35-18.111" *)
  \$paramod\reclocking\WIDTH=s32'00000000000000000000000000001000  \gen_reclocking[1].reclocking_i0  (
    .clk(clk),
    .data_in(\data_sync[1] ),
    .data_out(data_out)
  );
  assign \data_sync[0]  = data_in;
  assign \data_sync[2]  = data_out;
endmodule

(* dynports =  1  *)
(* hdlname = "spi_reg" *)
(* src = "spi_reg.sv:7.1-244.10" *)
module \$paramod$e280f0e9b751ed9f335b4a31654a0b08c7f1edad\spi_reg (clk, rstb, ena, spi_mosi, spi_miso, spi_clk, spi_cs_n, reg_addr, reg_data_i, reg_data_o, reg_addr_v, reg_data_i_dv, reg_data_o_dv, reg_rw, txn_width);
  (* src = "spi_reg.sv:11.18-11.21" *)
  input clk;
  wire clk;
  (* src = "spi_reg.sv:12.18-12.22" *)
  input rstb;
  wire rstb;
  (* src = "spi_reg.sv:13.18-13.21" *)
  input ena;
  wire ena;
  (* src = "spi_reg.sv:14.18-14.26" *)
  input spi_mosi;
  wire spi_mosi;
  (* src = "spi_reg.sv:15.18-15.26" *)
  output spi_miso;
  wire spi_miso;
  (* src = "spi_reg.sv:16.18-16.25" *)
  input spi_clk;
  wire spi_clk;
  (* src = "spi_reg.sv:17.18-17.26" *)
  input spi_cs_n;
  wire spi_cs_n;
  (* src = "spi_reg.sv:18.31-18.39" *)
  output [5:0] reg_addr;
  wire [5:0] reg_addr;
  (* src = "spi_reg.sv:19.30-19.40" *)
  input [31:0] reg_data_i;
  wire [31:0] reg_data_i;
  (* src = "spi_reg.sv:20.30-20.40" *)
  output [31:0] reg_data_o;
  wire [31:0] reg_data_o;
  (* src = "spi_reg.sv:21.18-21.28" *)
  output reg_addr_v;
  wire reg_addr_v;
  (* src = "spi_reg.sv:22.18-22.31" *)
  input reg_data_i_dv;
  wire reg_data_i_dv;
  (* src = "spi_reg.sv:23.18-23.31" *)
  output reg_data_o_dv;
  wire reg_data_o_dv;
  (* src = "spi_reg.sv:24.18-24.24" *)
  output reg_rw;
  reg reg_rw;
  (* src = "spi_reg.sv:25.24-25.33" *)
  output [1:0] txn_width;
  reg [1:0] txn_width;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  (* force_downto = 32'd1 *)
  (* src = "spi_reg.sv:162.14-162.14|spi_reg.sv:156.9-173.16|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [31:0] _138_;
  (* src = "spi_reg.sv:194.22-194.26" *)
  reg [5:0] addr;
  (* src = "spi_reg.sv:82.15-82.29" *)
  reg [5:0] buffer_counter;
  (* src = "spi_reg.sv:218.9-218.11" *)
  reg dv;
  (* src = "spi_reg.sv:33.9-33.12" *)
  wire eof;
  (* src = "spi_reg.sv:29.9-29.12" *)
  wire sof;
  (* src = "spi_reg.sv:39.9-39.20" *)
  wire spi_clk_neg;
  (* src = "spi_reg.sv:38.9-38.20" *)
  wire spi_clk_pos;
  (* onehot = 32'd1 *)
  reg [5:0] state;
  (* src = "spi_reg.sv:85.9-85.23" *)
  wire tx_buffer_load;
  (* src = "spi_reg.sv:148.21-148.31" *)
  reg [31:0] txn_buffer;
  assign _009_ = ~state[0];
  assign _010_ = ~state[1];
  assign _011_ = ~spi_mosi;
  assign _012_ = ~reg_rw;
  assign _013_ = ~(reg_data_i[30] & state[1]);
  assign _014_ = ~(buffer_counter[1] | buffer_counter[0]);
  assign _015_ = ~(buffer_counter[2] | buffer_counter[3]);
  assign _016_ = _014_ & _015_;
  assign _017_ = ~(buffer_counter[4] | buffer_counter[5]);
  assign _018_ = ~(_016_ & _017_);
  assign _019_ = spi_clk_neg & ~(spi_cs_n);
  assign _020_ = _018_ & _019_;
  assign _021_ = ~(state[4] & _020_);
  assign _022_ = spi_clk_pos & ~(spi_cs_n);
  assign _023_ = ~(state[0] | state[1]);
  assign _024_ = _023_ & ~(state[4]);
  assign _025_ = ~(_022_ & _024_);
  assign _026_ = ~(_021_ & _025_);
  assign _027_ = ~(txn_buffer[29] & _026_);
  assign _138_[30] = ~(_013_ & _027_);
  assign _028_ = ~(state[1] & reg_data_i[29]);
  assign _029_ = ~(txn_buffer[28] & _026_);
  assign _138_[29] = ~(_028_ & _029_);
  assign _030_ = ~(state[1] & reg_data_i[28]);
  assign _031_ = ~(txn_buffer[27] & _026_);
  assign _138_[28] = ~(_030_ & _031_);
  assign _032_ = ~(state[1] & reg_data_i[27]);
  assign _033_ = ~(txn_buffer[26] & _026_);
  assign _138_[27] = ~(_032_ & _033_);
  assign _034_ = ~(state[1] & reg_data_i[26]);
  assign _035_ = ~(txn_buffer[25] & _026_);
  assign _138_[26] = ~(_034_ & _035_);
  assign _036_ = ~(state[1] & reg_data_i[25]);
  assign _037_ = ~(txn_buffer[24] & _026_);
  assign _138_[25] = ~(_036_ & _037_);
  assign _038_ = ~(state[1] & reg_data_i[24]);
  assign _039_ = ~(txn_buffer[23] & _026_);
  assign _138_[24] = ~(_038_ & _039_);
  assign _040_ = ~(state[1] & reg_data_i[23]);
  assign _041_ = ~(txn_buffer[22] & _026_);
  assign _138_[23] = ~(_040_ & _041_);
  assign _042_ = ~(state[1] & reg_data_i[22]);
  assign _043_ = ~(txn_buffer[21] & _026_);
  assign _138_[22] = ~(_042_ & _043_);
  assign _044_ = ~(state[1] & reg_data_i[21]);
  assign _045_ = ~(txn_buffer[20] & _026_);
  assign _138_[21] = ~(_044_ & _045_);
  assign _046_ = ~(state[1] & reg_data_i[20]);
  assign _047_ = ~(txn_buffer[19] & _026_);
  assign _138_[20] = ~(_046_ & _047_);
  assign _048_ = ~(state[1] & reg_data_i[19]);
  assign _049_ = ~(txn_buffer[18] & _026_);
  assign _138_[19] = ~(_048_ & _049_);
  assign _050_ = ~(state[1] & reg_data_i[18]);
  assign _051_ = ~(txn_buffer[17] & _026_);
  assign _138_[18] = ~(_050_ & _051_);
  assign _052_ = ~(state[1] & reg_data_i[17]);
  assign _053_ = ~(txn_buffer[16] & _026_);
  assign _138_[17] = ~(_052_ & _053_);
  assign _054_ = ~(state[1] & reg_data_i[16]);
  assign _055_ = ~(txn_buffer[15] & _026_);
  assign _138_[16] = ~(_054_ & _055_);
  assign _056_ = ~(state[1] & reg_data_i[15]);
  assign _057_ = ~(txn_buffer[14] & _026_);
  assign _138_[15] = ~(_056_ & _057_);
  assign _058_ = ~(state[1] & reg_data_i[14]);
  assign _059_ = ~(txn_buffer[13] & _026_);
  assign _138_[14] = ~(_058_ & _059_);
  assign _060_ = ~(state[1] & reg_data_i[13]);
  assign _061_ = ~(txn_buffer[12] & _026_);
  assign _138_[13] = ~(_060_ & _061_);
  assign _062_ = ~(state[1] & reg_data_i[12]);
  assign _063_ = ~(txn_buffer[11] & _026_);
  assign _138_[12] = ~(_062_ & _063_);
  assign _064_ = ~(state[1] & reg_data_i[11]);
  assign _065_ = ~(txn_buffer[10] & _026_);
  assign _138_[11] = ~(_064_ & _065_);
  assign _066_ = ~(state[1] & reg_data_i[10]);
  assign _067_ = ~(txn_buffer[9] & _026_);
  assign _138_[10] = ~(_066_ & _067_);
  assign _068_ = ~(state[1] & reg_data_i[9]);
  assign _069_ = ~(txn_buffer[8] & _026_);
  assign _138_[9] = ~(_068_ & _069_);
  assign _070_ = ~(state[1] & reg_data_i[8]);
  assign _071_ = ~(txn_buffer[7] & _026_);
  assign _138_[8] = ~(_070_ & _071_);
  assign _072_ = ~(state[1] & reg_data_i[7]);
  assign _073_ = ~(txn_buffer[6] & _026_);
  assign _138_[7] = ~(_072_ & _073_);
  assign _074_ = ~(state[1] & reg_data_i[6]);
  assign _075_ = ~(txn_buffer[5] & _026_);
  assign _138_[6] = ~(_074_ & _075_);
  assign _076_ = ~(state[1] & reg_data_i[5]);
  assign _077_ = ~(txn_buffer[4] & _026_);
  assign _138_[5] = ~(_076_ & _077_);
  assign _078_ = ~(state[1] & reg_data_i[4]);
  assign _079_ = ~(txn_buffer[3] & _026_);
  assign _138_[4] = ~(_078_ & _079_);
  assign _080_ = ~(state[1] & reg_data_i[3]);
  assign _081_ = ~(txn_buffer[2] & _026_);
  assign _138_[3] = ~(_080_ & _081_);
  assign _082_ = ~(state[1] & reg_data_i[2]);
  assign _083_ = ~(txn_buffer[1] & _026_);
  assign _138_[2] = ~(_082_ & _083_);
  assign _084_ = ~(state[1] & reg_data_i[1]);
  assign _085_ = ~(txn_buffer[0] & _026_);
  assign _138_[1] = ~(_084_ & _085_);
  assign _086_ = _011_ | _025_;
  assign _087_ = ~(state[1] & reg_data_i[0]);
  assign _138_[0] = ~(_086_ & _087_);
  assign _088_ = ~(state[1] & reg_data_i[31]);
  assign _089_ = ~(txn_buffer[30] & _026_);
  assign _138_[31] = ~(_088_ & _089_);
  assign _090_ = buffer_counter[1] & buffer_counter[0];
  assign _091_ = buffer_counter[2] & _090_;
  assign _092_ = buffer_counter[3] & _091_;
  assign _093_ = ~(buffer_counter[4] & _092_);
  assign _094_ = buffer_counter[4] | _092_;
  assign _095_ = _022_ & _094_;
  assign _136_ = _093_ & _095_;
  assign _096_ = buffer_counter[3] | _091_;
  assign _097_ = _022_ & _096_;
  assign _135_ = _097_ & ~(_092_);
  assign _098_ = buffer_counter[2] | _090_;
  assign _099_ = _022_ & _098_;
  assign _134_ = _099_ & ~(_091_);
  assign _100_ = _022_ & ~(_014_);
  assign _133_ = _100_ & ~(_090_);
  assign _101_ = buffer_counter[5] & ~(buffer_counter[4]);
  assign _102_ = _016_ & _101_;
  assign _103_ = _022_ & ~(_102_);
  assign _132_ = _103_ & ~(buffer_counter[0]);
  assign _104_ = ~(state[4] | state[5]);
  assign _105_ = ~(ena & eof);
  assign _106_ = ena & _102_;
  assign _107_ = _105_ & ~(_106_);
  assign _108_ = _104_ | _107_;
  assign _109_ = state[3] & ~(_105_);
  assign _110_ = _102_ | ~(_109_);
  assign _111_ = ~(ena & sof);
  assign _112_ = ~(state[0] & _111_);
  assign _113_ = _110_ & _112_;
  assign _000_ = ~(_108_ & _113_);
  assign _114_ = ~(ena & reg_data_i_dv);
  assign _115_ = ~(state[1] & _114_);
  assign _116_ = ~(ena & state[2]);
  assign _117_ = reg_rw | _116_;
  assign _001_ = ~(_115_ & _117_);
  assign _008_ = state[3] & _106_;
  assign _118_ = state[2] & ~(ena);
  assign _002_ = _008_ | _118_;
  assign _119_ = _009_ | _111_;
  assign _120_ = ~(state[3] & _107_);
  assign _003_ = ~(_119_ & _120_);
  assign _121_ = _010_ | _114_;
  assign _122_ = ~(state[4] & _107_);
  assign _004_ = ~(_121_ & _122_);
  assign _123_ = ~(state[5] & _107_);
  assign _124_ = _012_ | _116_;
  assign _005_ = ~(_123_ & _124_);
  assign _125_ = _020_ | ~(state[4]);
  assign _126_ = _022_ | ~(_024_);
  assign _127_ = ena & _126_;
  assign _006_ = _125_ & _127_;
  assign _128_ = _022_ | _102_;
  assign _007_ = ena & _128_;
  assign _129_ = reg_rw & state[5];
  assign _131_ = _102_ & _129_;
  assign _130_ = ~(buffer_counter[5] ^ _093_);
  assign _137_ = _103_ & _130_;
  assign spi_miso = state[4] & txn_buffer[31];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:228.3-239.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) dv <= 1'h0;
    else if (ena) dv <= _131_;
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) reg_rw <= 1'h0;
    else if (_008_) reg_rw <= txn_buffer[31];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_width[0] <= 1'h1;
    else if (_008_) txn_width[0] <= txn_buffer[29];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_width[1] <= 1'h1;
    else if (_008_) txn_width[1] <= txn_buffer[30];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) addr[0] <= 1'h0;
    else if (_008_) addr[0] <= txn_buffer[0];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) addr[1] <= 1'h0;
    else if (_008_) addr[1] <= txn_buffer[1];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) addr[2] <= 1'h0;
    else if (_008_) addr[2] <= txn_buffer[2];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) addr[3] <= 1'h0;
    else if (_008_) addr[3] <= txn_buffer[3];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) addr[4] <= 1'h0;
    else if (_008_) addr[4] <= txn_buffer[4];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:197.3-211.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) addr[5] <= 1'h0;
    else if (_008_) addr[5] <= txn_buffer[5];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:179.3-191.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) buffer_counter[0] <= 1'h0;
    else if (_007_) buffer_counter[0] <= _132_;
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:179.3-191.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) buffer_counter[1] <= 1'h0;
    else if (_007_) buffer_counter[1] <= _133_;
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:179.3-191.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) buffer_counter[2] <= 1'h0;
    else if (_007_) buffer_counter[2] <= _134_;
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:179.3-191.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) buffer_counter[3] <= 1'h0;
    else if (_007_) buffer_counter[3] <= _135_;
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:179.3-191.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) buffer_counter[4] <= 1'h0;
    else if (_007_) buffer_counter[4] <= _136_;
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:179.3-191.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) buffer_counter[5] <= 1'h0;
    else if (_007_) buffer_counter[5] <= _137_;
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[0] <= 1'h0;
    else if (_006_) txn_buffer[0] <= _138_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[1] <= 1'h0;
    else if (_006_) txn_buffer[1] <= _138_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[2] <= 1'h0;
    else if (_006_) txn_buffer[2] <= _138_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[3] <= 1'h0;
    else if (_006_) txn_buffer[3] <= _138_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[4] <= 1'h0;
    else if (_006_) txn_buffer[4] <= _138_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[5] <= 1'h0;
    else if (_006_) txn_buffer[5] <= _138_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[6] <= 1'h0;
    else if (_006_) txn_buffer[6] <= _138_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[7] <= 1'h0;
    else if (_006_) txn_buffer[7] <= _138_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[8] <= 1'h0;
    else if (_006_) txn_buffer[8] <= _138_[8];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[9] <= 1'h0;
    else if (_006_) txn_buffer[9] <= _138_[9];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[10] <= 1'h0;
    else if (_006_) txn_buffer[10] <= _138_[10];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[11] <= 1'h0;
    else if (_006_) txn_buffer[11] <= _138_[11];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[12] <= 1'h0;
    else if (_006_) txn_buffer[12] <= _138_[12];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[13] <= 1'h0;
    else if (_006_) txn_buffer[13] <= _138_[13];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[14] <= 1'h0;
    else if (_006_) txn_buffer[14] <= _138_[14];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[15] <= 1'h0;
    else if (_006_) txn_buffer[15] <= _138_[15];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[16] <= 1'h0;
    else if (_006_) txn_buffer[16] <= _138_[16];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[17] <= 1'h0;
    else if (_006_) txn_buffer[17] <= _138_[17];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[18] <= 1'h0;
    else if (_006_) txn_buffer[18] <= _138_[18];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[19] <= 1'h0;
    else if (_006_) txn_buffer[19] <= _138_[19];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[20] <= 1'h0;
    else if (_006_) txn_buffer[20] <= _138_[20];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[21] <= 1'h0;
    else if (_006_) txn_buffer[21] <= _138_[21];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[22] <= 1'h0;
    else if (_006_) txn_buffer[22] <= _138_[22];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[23] <= 1'h0;
    else if (_006_) txn_buffer[23] <= _138_[23];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[24] <= 1'h0;
    else if (_006_) txn_buffer[24] <= _138_[24];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[25] <= 1'h0;
    else if (_006_) txn_buffer[25] <= _138_[25];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[26] <= 1'h0;
    else if (_006_) txn_buffer[26] <= _138_[26];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[27] <= 1'h0;
    else if (_006_) txn_buffer[27] <= _138_[27];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[28] <= 1'h0;
    else if (_006_) txn_buffer[28] <= _138_[28];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[29] <= 1'h0;
    else if (_006_) txn_buffer[29] <= _138_[29];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[30] <= 1'h0;
    else if (_006_) txn_buffer[30] <= _138_[30];
  (* \always_ff  = 32'd1 *)
  (* src = "spi_reg.sv:151.3-176.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) txn_buffer[31] <= 1'h0;
    else if (_006_) txn_buffer[31] <= _138_[31];
  always @(posedge clk, negedge rstb)
    if (!rstb) state[0] <= 1'h1;
    else state[0] <= _000_;
  always @(posedge clk, negedge rstb)
    if (!rstb) state[1] <= 1'h0;
    else state[1] <= _001_;
  always @(posedge clk, negedge rstb)
    if (!rstb) state[2] <= 1'h0;
    else state[2] <= _002_;
  always @(posedge clk, negedge rstb)
    if (!rstb) state[3] <= 1'h0;
    else state[3] <= _003_;
  always @(posedge clk, negedge rstb)
    if (!rstb) state[4] <= 1'h0;
    else state[4] <= _004_;
  always @(posedge clk, negedge rstb)
    if (!rstb) state[5] <= 1'h0;
    else state[5] <= _005_;
  (* module_not_derived = 32'd1 *)
  (* src = "spi_reg.sv:31.25-31.119" *)
  falling_edge_detector falling_edge_detector_sof (
    .clk(clk),
    .data(spi_cs_n),
    .ena(ena),
    .neg_edge(sof),
    .rstb(rstb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "spi_reg.sv:44.25-44.130" *)
  falling_edge_detector falling_edge_detector_spi_clk (
    .clk(clk),
    .data(spi_clk),
    .ena(ena),
    .neg_edge(spi_clk_neg),
    .rstb(rstb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "spi_reg.sv:35.24-35.117" *)
  rising_edge_detector rising_edge_detector_eof (
    .clk(clk),
    .data(spi_cs_n),
    .ena(ena),
    .pos_edge(eof),
    .rstb(rstb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "spi_reg.sv:42.24-42.128" *)
  rising_edge_detector rising_edge_detector_spi_clk (
    .clk(clk),
    .data(spi_clk),
    .ena(ena),
    .pos_edge(spi_clk_pos),
    .rstb(rstb)
  );
  assign reg_addr = addr;
  assign reg_addr_v = state[1];
  assign reg_data_o = txn_buffer;
  assign reg_data_o_dv = dv;
  assign tx_buffer_load = state[1];
endmodule

(* dynports =  1  *)
(* hdlname = "reclocking" *)
(* src = "reclocking.sv:6.1-21.10" *)
module \$paramod\reclocking\WIDTH=s32'00000000000000000000000000000001 (clk, data_in, data_out);
  (* src = "reclocking.sv:8.15-8.18" *)
  input clk;
  wire clk;
  (* src = "reclocking.sv:9.27-9.34" *)
  input [0:0] data_in;
  wire [0:0] data_in;
  (* src = "reclocking.sv:11.28-11.36" *)
  output [0:0] data_out;
  wire [0:0] data_out;
  (* src = "reclocking.sv:13.21-13.30" *)
  reg [0:0] data_sync;
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync <= data_in;
  assign data_out = data_sync;
endmodule

(* dynports =  1  *)
(* hdlname = "reclocking" *)
(* src = "reclocking.sv:6.1-21.10" *)
module \$paramod\reclocking\WIDTH=s32'00000000000000000000000000001000 (clk, data_in, data_out);
  (* src = "reclocking.sv:8.15-8.18" *)
  input clk;
  wire clk;
  (* src = "reclocking.sv:9.27-9.34" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "reclocking.sv:11.28-11.36" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "reclocking.sv:13.21-13.30" *)
  reg [7:0] data_sync;
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[0] <= data_in[0];
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[1] <= data_in[1];
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[2] <= data_in[2];
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[3] <= data_in[3];
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[4] <= data_in[4];
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[5] <= data_in[5];
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[6] <= data_in[6];
  (* \always_ff  = 32'd1 *)
  (* src = "reclocking.sv:15.3-17.6" *)
  always @(posedge clk)
    data_sync[7] <= data_in[7];
  assign data_out = data_sync;
endmodule

(* src = "falling_edge_detector.sv:6.1-29.10" *)
module falling_edge_detector(rstb, clk, ena, data, neg_edge);
  (* src = "falling_edge_detector.sv:8.15-8.19" *)
  input rstb;
  wire rstb;
  (* src = "falling_edge_detector.sv:9.15-9.18" *)
  input clk;
  wire clk;
  (* src = "falling_edge_detector.sv:10.15-10.18" *)
  input ena;
  wire ena;
  (* src = "falling_edge_detector.sv:11.15-11.19" *)
  input data;
  wire data;
  (* src = "falling_edge_detector.sv:13.16-13.24" *)
  output neg_edge;
  wire neg_edge;
  (* src = "falling_edge_detector.sv:15.9-15.17" *)
  reg data_dly;
  assign neg_edge = data_dly & ~(data);
  (* \always_ff  = 32'd1 *)
  (* src = "falling_edge_detector.sv:17.3-25.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) data_dly <= 1'h0;
    else if (ena) data_dly <= data;
endmodule

(* src = "rising_edge_detector.sv:6.1-29.10" *)
module rising_edge_detector(rstb, clk, ena, data, pos_edge);
  (* src = "rising_edge_detector.sv:8.15-8.19" *)
  input rstb;
  wire rstb;
  (* src = "rising_edge_detector.sv:9.15-9.18" *)
  input clk;
  wire clk;
  (* src = "rising_edge_detector.sv:10.15-10.18" *)
  input ena;
  wire ena;
  (* src = "rising_edge_detector.sv:11.15-11.19" *)
  input data;
  wire data;
  (* src = "rising_edge_detector.sv:13.16-13.24" *)
  output pos_edge;
  wire pos_edge;
  (* src = "rising_edge_detector.sv:15.9-15.17" *)
  reg data_dly;
  assign pos_edge = data & ~(data_dly);
  (* \always_ff  = 32'd1 *)
  (* src = "rising_edge_detector.sv:17.3-25.6" *)
  always @(posedge clk, negedge rstb)
    if (!rstb) data_dly <= 1'h0;
    else if (ena) data_dly <= data;
endmodule

(* src = "peripheral.v:11.1-86.10" *)
module tqvp_example(clk, rst_n, ui_in, uo_out, address, data_in, data_write_n, data_read_n, data_out, data_ready, user_interrupt);
  (* src = "peripheral.v:12.19-12.22" *)
  input clk;
  wire clk;
  (* src = "peripheral.v:13.19-13.24" *)
  input rst_n;
  wire rst_n;
  (* src = "peripheral.v:15.19-15.24" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "peripheral.v:18.19-18.25" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  (* src = "peripheral.v:21.19-21.26" *)
  input [5:0] address;
  wire [5:0] address;
  (* src = "peripheral.v:22.19-22.26" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "peripheral.v:25.19-25.31" *)
  input [1:0] data_write_n;
  wire [1:0] data_write_n;
  (* src = "peripheral.v:26.19-26.30" *)
  input [1:0] data_read_n;
  wire [1:0] data_read_n;
  (* src = "peripheral.v:28.19-28.27" *)
  output [31:0] data_out;
  wire [31:0] data_out;
  (* src = "peripheral.v:29.19-29.29" *)
  output data_ready;
  wire data_ready;
  (* src = "peripheral.v:31.19-31.33" *)
  output user_interrupt;
  wire user_interrupt;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  (* src = "peripheral.v:70.13-70.38" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  (* src = "peripheral.v:84.10-84.17" *)
  wire _unused;
  (* src = "peripheral.v:35.16-35.28" *)
  reg [31:0] example_data;
  (* src = "peripheral.v:62.9-62.26" *)
  reg example_interrupt;
  (* src = "peripheral.v:63.9-63.21" *)
  reg last_ui_in_6;
  assign _061_ = ~(example_data[6] & ui_in[6]);
  assign _005_ = example_data[6] ^ ui_in[6];
  assign _006_ = ~(example_data[5] & ui_in[5]);
  assign _007_ = example_data[5] | ui_in[5];
  assign _008_ = ~(example_data[4] & ui_in[4]);
  assign _009_ = example_data[4] ^ ui_in[4];
  assign _010_ = ~(example_data[3] & ui_in[3]);
  assign _011_ = example_data[3] | ui_in[3];
  assign _012_ = ~(example_data[2] & ui_in[2]);
  assign _013_ = ~(example_data[1] & ui_in[1]);
  assign _014_ = example_data[0] & ui_in[0];
  assign _015_ = example_data[1] ^ ui_in[1];
  assign _016_ = ~(_014_ & _015_);
  assign _017_ = ~(_013_ & _016_);
  assign _018_ = example_data[2] ^ ui_in[2];
  assign _019_ = ~(_017_ & _018_);
  assign _020_ = ~(_012_ & _019_);
  assign _021_ = ~(_011_ & _020_);
  assign _022_ = ~(_010_ & _021_);
  assign _023_ = ~(_009_ & _022_);
  assign _024_ = ~(_008_ & _023_);
  assign _025_ = ~(_007_ & _024_);
  assign _026_ = ~(_006_ & _025_);
  assign _027_ = ~(_005_ & _026_);
  assign _028_ = ~(_061_ & _027_);
  assign _029_ = ~(example_data[7] ^ ui_in[7]);
  assign uo_out[7] = ~(_028_ ^ _029_);
  assign uo_out[6] = _005_ ^ _026_;
  assign _030_ = ~(_006_ & _007_);
  assign uo_out[5] = ~(_024_ ^ _030_);
  assign uo_out[4] = _009_ ^ _022_;
  assign _031_ = ~(_010_ & _011_);
  assign uo_out[3] = ~(_020_ ^ _031_);
  assign uo_out[2] = _017_ ^ _018_;
  assign uo_out[1] = _014_ ^ _015_;
  assign uo_out[0] = example_data[0] ^ ui_in[0];
  assign _032_ = ~(address[4] | address[1]);
  assign _033_ = ~(address[0] | address[5]);
  assign _034_ = _032_ & _033_;
  assign _035_ = _034_ & ~(address[2]);
  assign _036_ = _035_ & ~(address[3]);
  assign data_out[30] = example_data[30] & _036_;
  assign data_out[29] = example_data[29] & _036_;
  assign data_out[28] = example_data[28] & _036_;
  assign data_out[27] = example_data[27] & _036_;
  assign data_out[26] = example_data[26] & _036_;
  assign data_out[25] = example_data[25] & _036_;
  assign data_out[24] = example_data[24] & _036_;
  assign data_out[23] = example_data[23] & _036_;
  assign data_out[22] = example_data[22] & _036_;
  assign data_out[21] = example_data[21] & _036_;
  assign data_out[20] = example_data[20] & _036_;
  assign data_out[19] = example_data[19] & _036_;
  assign data_out[18] = example_data[18] & _036_;
  assign data_out[17] = example_data[17] & _036_;
  assign data_out[16] = example_data[16] & _036_;
  assign data_out[15] = example_data[15] & _036_;
  assign data_out[14] = example_data[14] & _036_;
  assign data_out[13] = example_data[13] & _036_;
  assign data_out[12] = example_data[12] & _036_;
  assign data_out[11] = example_data[11] & _036_;
  assign data_out[10] = example_data[10] & _036_;
  assign data_out[9] = example_data[9] & _036_;
  assign data_out[8] = example_data[8] & _036_;
  assign _037_ = address[2] & ~(address[3]);
  assign _038_ = _034_ & _037_;
  assign _039_ = ~(ui_in[7] & _038_);
  assign _040_ = ~(example_data[7] & _036_);
  assign data_out[7] = ~(_039_ & _040_);
  assign _041_ = ~(ui_in[6] & _038_);
  assign _042_ = ~(example_data[6] & _036_);
  assign data_out[6] = ~(_041_ & _042_);
  assign _043_ = ~(ui_in[5] & _038_);
  assign _044_ = ~(example_data[5] & _036_);
  assign data_out[5] = ~(_043_ & _044_);
  assign _045_ = ~(ui_in[4] & _038_);
  assign _046_ = ~(example_data[4] & _036_);
  assign data_out[4] = ~(_045_ & _046_);
  assign _047_ = ~(ui_in[3] & _038_);
  assign _048_ = ~(example_data[3] & _036_);
  assign data_out[3] = ~(_047_ & _048_);
  assign _049_ = ~(ui_in[2] & _038_);
  assign _050_ = ~(example_data[2] & _036_);
  assign data_out[2] = ~(_049_ & _050_);
  assign _051_ = ~(ui_in[1] & _038_);
  assign _052_ = ~(example_data[1] & _036_);
  assign data_out[1] = ~(_051_ & _052_);
  assign _053_ = ~(ui_in[0] & _038_);
  assign _054_ = ~(example_data[0] & _036_);
  assign data_out[0] = ~(_053_ & _054_);
  assign _055_ = ~(data_write_n[0] & data_write_n[1]);
  assign _056_ = address[3] & data_in[0];
  assign _057_ = _055_ & _056_;
  assign _058_ = ~(_035_ & _057_);
  assign _000_ = ~(rst_n & _058_);
  assign _001_ = _036_ & _055_;
  assign _059_ = data_write_n[0] | data_write_n[1];
  assign _002_ = _001_ & _059_;
  assign _060_ = data_write_n[1] & ~(data_write_n[0]);
  assign _003_ = _036_ & _060_;
  assign _004_ = ui_in[6] & ~(last_ui_in_6);
  assign data_out[31] = example_data[31] & _036_;
  (* src = "peripheral.v:65.5-77.8" *)
  always @(posedge clk)
    if (_004_) example_interrupt <= 1'h1;
    else if (_000_) example_interrupt <= 1'h0;
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[16] <= 1'h0;
    else if (_003_) example_data[16] <= data_in[16];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[17] <= 1'h0;
    else if (_003_) example_data[17] <= data_in[17];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[18] <= 1'h0;
    else if (_003_) example_data[18] <= data_in[18];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[19] <= 1'h0;
    else if (_003_) example_data[19] <= data_in[19];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[20] <= 1'h0;
    else if (_003_) example_data[20] <= data_in[20];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[21] <= 1'h0;
    else if (_003_) example_data[21] <= data_in[21];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[22] <= 1'h0;
    else if (_003_) example_data[22] <= data_in[22];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[23] <= 1'h0;
    else if (_003_) example_data[23] <= data_in[23];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[24] <= 1'h0;
    else if (_003_) example_data[24] <= data_in[24];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[25] <= 1'h0;
    else if (_003_) example_data[25] <= data_in[25];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[26] <= 1'h0;
    else if (_003_) example_data[26] <= data_in[26];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[27] <= 1'h0;
    else if (_003_) example_data[27] <= data_in[27];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[28] <= 1'h0;
    else if (_003_) example_data[28] <= data_in[28];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[29] <= 1'h0;
    else if (_003_) example_data[29] <= data_in[29];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[30] <= 1'h0;
    else if (_003_) example_data[30] <= data_in[30];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[31] <= 1'h0;
    else if (_003_) example_data[31] <= data_in[31];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[8] <= 1'h0;
    else if (_002_) example_data[8] <= data_in[8];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[9] <= 1'h0;
    else if (_002_) example_data[9] <= data_in[9];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[10] <= 1'h0;
    else if (_002_) example_data[10] <= data_in[10];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[11] <= 1'h0;
    else if (_002_) example_data[11] <= data_in[11];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[12] <= 1'h0;
    else if (_002_) example_data[12] <= data_in[12];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[13] <= 1'h0;
    else if (_002_) example_data[13] <= data_in[13];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[14] <= 1'h0;
    else if (_002_) example_data[14] <= data_in[14];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[15] <= 1'h0;
    else if (_002_) example_data[15] <= data_in[15];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[0] <= 1'h0;
    else if (_001_) example_data[0] <= data_in[0];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[1] <= 1'h0;
    else if (_001_) example_data[1] <= data_in[1];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[2] <= 1'h0;
    else if (_001_) example_data[2] <= data_in[2];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[3] <= 1'h0;
    else if (_001_) example_data[3] <= data_in[3];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[4] <= 1'h0;
    else if (_001_) example_data[4] <= data_in[4];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[5] <= 1'h0;
    else if (_001_) example_data[5] <= data_in[5];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[6] <= 1'h0;
    else if (_001_) example_data[6] <= data_in[6];
  (* src = "peripheral.v:36.5-46.8" *)
  always @(posedge clk)
    if (!rst_n) example_data[7] <= 1'h0;
    else if (_001_) example_data[7] <= data_in[7];
  (* src = "peripheral.v:65.5-77.8" *)
  always @(posedge clk)
    last_ui_in_6 <= ui_in[6];
  assign _unused = 1'h0;
  assign data_ready = 1'h1;
  assign user_interrupt = example_interrupt;
endmodule

(* top =  1  *)
(* src = "tt_wrapper.v:9.1-132.10" *)
module tt_um_tqv_peripheral_harness(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  (* src = "tt_wrapper.v:10.23-10.28" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "tt_wrapper.v:11.23-11.29" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  (* src = "tt_wrapper.v:12.23-12.29" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "tt_wrapper.v:13.23-13.30" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "tt_wrapper.v:14.23-14.29" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "tt_wrapper.v:15.23-15.26" *)
  input ena;
  wire ena;
  (* src = "tt_wrapper.v:16.23-16.26" *)
  input clk;
  wire clk;
  (* src = "tt_wrapper.v:17.23-17.28" *)
  input rst_n;
  wire rst_n;
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "tt_wrapper.v:130.8-130.15" *)
  wire _unused;
  (* src = "tt_wrapper.v:56.8-56.18" *)
  wire addr_valid;
  (* src = "tt_wrapper.v:21.14-21.21" *)
  wire [5:0] address;
  (* src = "tt_wrapper.v:22.15-22.22" *)
  wire [31:0] data_in;
  (* src = "tt_wrapper.v:23.15-23.23" *)
  wire [31:0] data_out;
  (* src = "tt_wrapper.v:60.14-60.29" *)
  wire [31:0] data_out_masked;
  (* src = "tt_wrapper.v:25.13-25.24" *)
  wire [1:0] data_read_n;
  (* src = "tt_wrapper.v:26.8-26.18" *)
  wire data_ready;
  (* src = "tt_wrapper.v:58.8-58.15" *)
  wire data_rw;
  (* src = "tt_wrapper.v:57.8-57.18" *)
  wire data_valid;
  (* src = "tt_wrapper.v:24.13-24.25" *)
  wire [1:0] data_write_n;
  (* src = "tt_wrapper.v:35.7-35.16" *)
  reg rst_reg_n;
  (* src = "tt_wrapper.v:64.8-64.15" *)
  wire spi_clk;
  (* src = "tt_wrapper.v:70.8-70.20" *)
  wire spi_clk_sync;
  (* src = "tt_wrapper.v:63.8-63.16" *)
  wire spi_cs_n;
  (* src = "tt_wrapper.v:69.8-69.21" *)
  wire spi_cs_n_sync;
  (* src = "tt_wrapper.v:65.8-65.16" *)
  wire spi_miso;
  (* src = "tt_wrapper.v:66.8-66.16" *)
  wire spi_mosi;
  (* src = "tt_wrapper.v:71.8-71.21" *)
  wire spi_mosi_sync;
  (* src = "tt_wrapper.v:59.14-59.19" *)
  wire [1:0] txn_n;
  (* src = "tt_wrapper.v:30.13-30.23" *)
  wire [7:0] ui_in_sync;
  (* src = "tt_wrapper.v:27.8-27.22" *)
  wire user_interrupt;
  assign _00_ = ~(data_valid & data_rw);
  assign data_write_n[0] = txn_n[0] | _00_;
  assign _01_ = data_rw | ~(addr_valid);
  assign data_read_n[0] = txn_n[0] | _01_;
  assign data_out_masked[30] = data_out[30] & txn_n[1];
  assign data_out_masked[29] = txn_n[1] & data_out[29];
  assign data_out_masked[28] = txn_n[1] & data_out[28];
  assign data_out_masked[27] = txn_n[1] & data_out[27];
  assign data_out_masked[26] = txn_n[1] & data_out[26];
  assign data_out_masked[25] = txn_n[1] & data_out[25];
  assign data_out_masked[24] = txn_n[1] & data_out[24];
  assign data_out_masked[23] = txn_n[1] & data_out[23];
  assign data_out_masked[22] = txn_n[1] & data_out[22];
  assign data_out_masked[21] = txn_n[1] & data_out[21];
  assign data_out_masked[20] = txn_n[1] & data_out[20];
  assign data_out_masked[19] = txn_n[1] & data_out[19];
  assign data_out_masked[18] = txn_n[1] & data_out[18];
  assign data_out_masked[17] = txn_n[1] & data_out[17];
  assign data_out_masked[16] = txn_n[1] & data_out[16];
  assign _02_ = txn_n[0] | txn_n[1];
  assign data_out_masked[14] = data_out[14] & _02_;
  assign data_out_masked[13] = data_out[13] & _02_;
  assign data_out_masked[12] = data_out[12] & _02_;
  assign data_out_masked[11] = data_out[11] & _02_;
  assign data_out_masked[10] = data_out[10] & _02_;
  assign data_out_masked[9] = data_out[9] & _02_;
  assign data_out_masked[8] = data_out[8] & _02_;
  assign data_out_masked[15] = data_out[15] & _02_;
  assign data_out_masked[31] = txn_n[1] & data_out[31];
  assign data_read_n[1] = txn_n[1] | _01_;
  assign data_write_n[1] = txn_n[1] | _00_;
  (* src = "tt_wrapper.v:37.3-37.44" *)
  always @(negedge clk)
    rst_reg_n <= rst_n;
  (* src = "tt_wrapper.v:82.37-98.4" *)
  \$paramod$e280f0e9b751ed9f335b4a31654a0b08c7f1edad\spi_reg  i_spi_reg (
    .clk(clk),
    .ena(1'h1),
    .reg_addr(address),
    .reg_addr_v(addr_valid),
    .reg_data_i({ data_out_masked[31:8], data_out[7:0] }),
    .reg_data_i_dv(data_ready),
    .reg_data_o(data_in),
    .reg_data_o_dv(data_valid),
    .reg_rw(data_rw),
    .rstb(rst_reg_n),
    .spi_clk(spi_clk_sync),
    .spi_cs_n(spi_cs_n_sync),
    .spi_miso(spi_miso),
    .spi_mosi(spi_mosi_sync),
    .txn_width(txn_n)
  );
  (* src = "tt_wrapper.v:78.41-78.124" *)
  \$paramod$1b0ac1a71bf6235a146509cbb11b370bdc3def37\synchronizer  synchronizer_spi_clk_inst (
    .clk(clk),
    .data_in(uio_in[5]),
    .data_out(spi_clk_sync)
  );
  (* src = "tt_wrapper.v:77.41-77.125" *)
  \$paramod$1b0ac1a71bf6235a146509cbb11b370bdc3def37\synchronizer  synchronizer_spi_cs_n_inst (
    .clk(clk),
    .data_in(uio_in[4]),
    .data_out(spi_cs_n_sync)
  );
  (* src = "tt_wrapper.v:79.41-79.125" *)
  \$paramod$1b0ac1a71bf6235a146509cbb11b370bdc3def37\synchronizer  synchronizer_spi_mosi_inst (
    .clk(clk),
    .data_in(uio_in[6]),
    .data_out(spi_mosi_sync)
  );
  (* src = "tt_wrapper.v:31.41-31.116" *)
  \$paramod$e209ecfe3425492cab30fe3f17f0ed06a3da57b8\synchronizer  synchronizer_ui_in_inst (
    .clk(clk),
    .data_in(ui_in),
    .data_out(ui_in_sync)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "tt_wrapper.v:41.16-53.4" *)
  tqvp_example user_peripheral (
    .address(address),
    .clk(clk),
    .data_in(data_in),
    .data_out(data_out),
    .data_read_n(data_read_n),
    .data_ready(data_ready),
    .data_write_n(data_write_n),
    .rst_n(rst_reg_n),
    .ui_in(ui_in_sync),
    .uo_out(uo_out),
    .user_interrupt(user_interrupt)
  );
  assign _unused = 1'h0;
  assign data_out_masked[7:0] = data_out[7:0];
  assign spi_clk = uio_in[5];
  assign spi_cs_n = uio_in[4];
  assign spi_mosi = uio_in[6];
  assign uio_oe = 8'h0b;
  assign uio_out = { 4'h0, spi_miso, 1'h0, data_ready, user_interrupt };
endmodule
